### ISSUE TITLE
Literals with line breaks are not rendered correctly

### ISSUE THREAD

**Issue by white-gecko** [AKSW/LDOW2016_PF_Client#6]
Literals with line breaks are not rendered correctly. Please see the attached screenshot:

![bildschirmfoto von 2016-04-03 12 43 12](https://cloud.githubusercontent.com/assets/1018168/14232016/f41f748e-f999-11e5-8a2f-5233d419a80b.png)

**Comment by white-gecko** [comment]
It would be cool, if one line literals and resources would still appear in an one line input. There is also a problem in this example for the feed property and the multi line literal is not correctly displayed regarding the quotation marks `"…"^^<datatype>`

**Comment by TBoonX** [comment]
Fixed.
Now we are using textboxes. In there you could use line breaks. when a patch is created, literals are parsed (escaping " and escaping line breaks). Works now with aksw/About
